### PR TITLE
feat: add `times.atMost` function

### PR DESCRIPTION
**Pull request by xRSquared**
Add `times.atMost` function for matching an expression at most N times.

## Usage
```js
import { createRegExp, exactly } from 'magic-regexp'

const fooRegex = createRegExp(exactly('foo').times.atMost(2)) // (?:foo){0,2}

const fooOnce = 'foo'
const fooTwice = 'foofoo'
const fooThrice = 'foofoofoo'

const testOne = fooOnce.replace(fooRegex.toString(), 'bye') // bye
const testTwo = fooTwice.replace(fooRegex.toString(), 'bye') // bye
const testThree = fooThrice.replace(fooRegex.toString(), 'bye') // byefoo
```

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
This looks great 👌 Thank you!

**Comment by darsh-agrawal71** [comment]
When will this be added in the npm package?

**Comment by danielroe** [comment]
Shortly 😊

**Comment by darsh-agrawal71** [comment]
thanks!

**Pull request merged**
